name: "📌Aggregation of exp"
description: Aggregate all related issues of correspondent `exp`!
title: "📌[exp-name] aggregation"
labels: "aggregation"
body:
  - type: textarea
    attributes:
      label: 📌 Description
      description: >-
        You can create aggregation starts with existing issues at the top of this issue, 
        or aggregate further issues later.
