name: Build gh_pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          docs:
            - 'docs/**'

  translate:
    runs-on: ubuntu-latest
    needs: docs-changes
    if: ${{ needs.changes.outputs.docs == 'true' }}
    strategy:
      matrix:
        include:
          - lang: "en"
    steps:
      - uses: actions/checkout@v4
      - name: translate-by-dify
        run: |
          cd docs
          # translation by dify from locate/zh to locate/${{ matrix.lang }}

  pages-deploy:
    runs-on: ubuntu-latest
    needs: translate
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd docs && npm install
      - name: Build VitePress docs
        run: |
          cd docs && npm run docs:build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
